Repository Zenika/deadoralive, pull requests merged in 2019-10, with the labels that each got.

#50 :recycle: Refactor hard mode
  src/game/Rockstar.svelte
Labels: enhancement

#54 :beers: Mentions légales
  public/global.css
  public/legalNotice.html
  src/Landing.svelte
  src/rockstars.js
Labels: chore

#56 :beers: Newsletters
  src/Landing.svelte
Labels: chore

#57 :lipstick: fix styles sur tablette
  public/global.css
  public/index.html
  src/Landing.svelte
Labels: bug

#53 :sparkles: Add a downsizing progress bar
  src/Landing.svelte
  src/game/ProgressBar.svelte
  src/game/Rockstar.svelte
  src/game/Rules.svelte
  src/game/Score.svelte
Labels: enhancement
